export const colorTokens = [
  { name: "--background", label: "Fondo" },
  { name: "--foreground", label: "Texto" },
  { name: "--card", label: "Panel" },
  { name: "--card-foreground", label: "Texto de panel" },
  { name: "--popover", label: "Superposición" },
  { name: "--popover-foreground", label: "Texto de superposición" },
  { name: "--primary", label: "Acción principal" },
  { name: "--primary-foreground", label: "Texto de acción principal" },
  { name: "--primary-hover", label: "Acción principal al señalar" },
  { name: "--secondary", label: "Acción secundaria" },
  { name: "--secondary-foreground", label: "Texto de acción secundaria" },
  { name: "--muted", label: "Superficie neutra" },
  { name: "--muted-foreground", label: "Texto secundario" },
  { name: "--accent", label: "Acento de interfaz" },
  { name: "--accent-foreground", label: "Texto de acento" },
  { name: "--link", label: "Enlace y foco" },
  { name: "--destructive", label: "Destructivo" },
  { name: "--destructive-foreground", label: "Texto destructivo" },
  { name: "--ring", label: "Indicador de foco" },
  { name: "--success", label: "Éxito" },
  { name: "--success-foreground", label: "Texto de éxito" },
  { name: "--warning", label: "Advertencia" },
  { name: "--warning-foreground", label: "Texto de advertencia" },
  { name: "--info", label: "Información" },
  { name: "--info-foreground", label: "Texto informativo" },
  { name: "--border", label: "Borde" },
  { name: "--input", label: "Borde de campo" },
  { name: "--brand-navy", label: "Azul institucional" },
  { name: "--faro", label: "Marca Faro" },
  { name: "--sidebar", label: "Navegación" },
  { name: "--sidebar-foreground", label: "Texto de navegación" },
  { name: "--sidebar-muted-foreground", label: "Texto secundario de navegación" },
  { name: "--sidebar-accent", label: "Superficie activa de navegación" },
  { name: "--sidebar-accent-foreground", label: "Texto de superficie activa" },
  { name: "--sidebar-primary", label: "Acción de navegación" },
  { name: "--sidebar-primary-foreground", label: "Texto de acción de navegación" },
  { name: "--sidebar-border", label: "Borde de navegación" },
  { name: "--sidebar-ring", label: "Foco de navegación" },
  { name: "--sidebar-marker", label: "Marca Faro en navegación" },
  { name: "--career-blue", label: "Carrera azul" },
  { name: "--career-blue-foreground", label: "Texto de carrera azul" },
  { name: "--career-emerald", label: "Carrera esmeralda" },
  { name: "--career-emerald-foreground", label: "Texto de carrera esmeralda" },
  { name: "--career-violet", label: "Carrera violeta" },
  { name: "--career-violet-foreground", label: "Texto de carrera violeta" },
  { name: "--career-yellow", label: "Carrera amarilla" },
  { name: "--career-yellow-foreground", label: "Texto de carrera amarilla" },
  { name: "--career-cyan", label: "Carrera cian" },
  { name: "--career-cyan-foreground", label: "Texto de carrera cian" },
  { name: "--career-magenta", label: "Carrera magenta" },
  { name: "--career-magenta-foreground", label: "Texto de carrera magenta" },
  { name: "--career-lime", label: "Carrera lima" },
  { name: "--career-lime-foreground", label: "Texto de carrera lima" },
  { name: "--career-graphite", label: "Carrera grafito" },
  { name: "--career-graphite-foreground", label: "Texto de carrera grafito" },
] as const;

export const careerPalette = [
  {
    hue: "blue",
    label: "Azul",
    career: "Ingeniería en Sistemas de Información",
  },
  {
    hue: "emerald",
    label: "Esmeralda",
    career: "Ingeniería Electromecánica",
  },
  { hue: "violet", label: "Violeta", career: "Ingeniería Química" },
  { hue: "yellow", label: "Amarillo", career: "Ingeniería Civil" },
  { hue: "cyan", label: "Cian", career: "Ingeniería Eléctrica" },
  { hue: "magenta", label: "Magenta", career: "Ingeniería Mecánica" },
  {
    hue: "lime",
    label: "Lima",
    career: "Licenciatura en Administración Rural",
  },
  {
    hue: "graphite",
    label: "Grafito",
    career: "Tecnicatura Universitaria en Programación",
  },
] as const;
